import java.util.*;

class Patient {
    String name;
    List<Doctor> doctors = new ArrayList<>();
    Patient(String name) { this.name = name; }
    void addDoctor(Doctor d) { doctors.add(d); }
}

class Doctor {
    String name;
    List<Patient> patients = new ArrayList<>();
    Doctor(String name) { this.name = name; }
    void consult(Patient p) {
        patients.add(p);
        p.addDoctor(this);
        System.out.println(name + " consults " + p.name);
    }
}

class Hospital {
    String name;
    List<Doctor> doctors = new ArrayList<>();
    List<Patient> patients = new ArrayList<>();
    Hospital(String name) { this.name = name; }
    void addDoctor(Doctor d) { doctors.add(d); }
    void addPatient(Patient p) { patients.add(p); }
}

public class Problem3 {
    public static void main(String[] args) {
        Hospital h = new Hospital("City Hospital");
        Doctor d1 = new Doctor("Dr. Patel");
        Doctor d2 = new Doctor("Dr. Mehta");
        Patient p1 = new Patient("Aman");
        Patient p2 = new Patient("Riya");
        h.addDoctor(d1);
        h.addDoctor(d2);
        h.addPatient(p1);
        h.addPatient(p2);
        d1.consult(p1);
        d2.consult(p1);
        d1.consult(p2);
    }
}
